server.port=9600
spring.datasource.url=jdbc:postgresql://localhost:5432/phdmi3
spring.datasource.password=123
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
