server.port=9600
spring.datasource.url=jdbc:postgresql://localhost:5432/????????
spring.datasource.password=?????
spring.datasource.username=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
